name: Daily Report

on:
  schedule:
    # 每天9点触发(UTC凌晨2点)
    - cron: "0 1 * * *"
  workflow_dispatch:


jobs:
  sendMsg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Send Report
        run: go run main.go
        env:
          BOT_URL: ${{ secrets.BOT_URL }}
          USERNAME: ${{ secrets.USERNAME }}
          WAKATIME_APIKEY: ${{ secrets.WAKATIME_APIKEY }}
